os:
  - linux
  - osx
language: go
go:
  - 1.8
install:
  - go get github.com/getgauge/gauge_screenshot
script:
  - if [[ $TRAVIS_OS_NAME == "linux " ]]; then export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start && sleep 3; fi
  - go test ./...
