version: 1.0.{build}
clone_folder: c:\gopath\src\github.com\getgauge\gauge_screenshot
environment:
  GOPATH: c:\gopath
init:
- ps: >-
    choco install mingw
    
    Write-Host "Done installing mingw"
build_script:
- ps: >-
    $env:Path = "C:\tools\mingw64;$env:GOPATH\bin;" + [System.Environment]::GetEnvironmentVariable("Path","Machine") + ";" + [System.Environment]::GetEnvironmentVariable("Path","User")
    
    go get github.com/getgauge/gauge_screenshot
test_script:
- ps: >-
    go test .\...
