version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.8
      
    working_directory: /go/src/github.com/getgauge/gauge_screenshot
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: xvfb-run go test -v ./...